-- Customer DM notification coverage fixes

ALTER TYPE "UserNotificationType" ADD VALUE 'COMPANY_VERIFICATION_REJECTED';
ALTER TYPE "UserNotificationType" ADD VALUE 'COMPANY_VERIFICATION_REVOKED';
ALTER TYPE "UserNotificationType" ADD VALUE 'ALTA_CARD_FROZEN';
ALTER TYPE "UserNotificationType" ADD VALUE 'ALTA_CARD_UNFROZEN';
ALTER TYPE "UserNotificationType" ADD VALUE 'CUSTOMER_PAYMENT_FAILED';
ALTER TYPE "UserNotificationType" ADD VALUE 'MERCHANT_RECURRING_INVOICE_FAILED';
ALTER TYPE "UserNotificationType" ADD VALUE 'MERCHANT_AUTOPAY_CONFIRMATION_REQUIRED';
ALTER TYPE "UserNotificationType" ADD VALUE 'COMMERCIAL_PRO_RENEWAL_REMINDER';
ALTER TYPE "UserNotificationType" ADD VALUE 'COMMERCIAL_BILLING_LOW_BALANCE_WARNING';
ALTER TYPE "UserNotificationType" ADD VALUE 'LARGE_MONEY_MOVEMENT_ALERT';
ALTER TYPE "UserNotificationType" ADD VALUE 'MERCHANT_FIRST_PAYMENT_RECEIVED';
