ALTER TYPE "UserNotificationType" ADD VALUE IF NOT EXISTS 'DEPOSIT_SUBMITTED';
ALTER TYPE "UserNotificationType" ADD VALUE IF NOT EXISTS 'WITHDRAWAL_SUBMITTED';
ALTER TYPE "UserNotificationType" ADD VALUE IF NOT EXISTS 'TRANSFER_COMPLETED';
ALTER TYPE "UserNotificationType" ADD VALUE IF NOT EXISTS 'ALTA_PAY_SENT';
