-- AlterEnum: Terminal Discord notification types (Phase 2)
ALTER TYPE "UserNotificationType" ADD VALUE IF NOT EXISTS 'TERMINAL_CRYPTO_ORDER_REJECTED';
ALTER TYPE "UserNotificationType" ADD VALUE IF NOT EXISTS 'TERMINAL_CRYPTO_ORDER_FAILED';
ALTER TYPE "UserNotificationType" ADD VALUE IF NOT EXISTS 'TERMINAL_FUNDING_COMPLETED';
ALTER TYPE "UserNotificationType" ADD VALUE IF NOT EXISTS 'TERMINAL_FUNDING_FAILED';
