/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as TerminalRouteRouteImport } from './routes/terminal/route'
import { Route as ExchangeRouteRouteImport } from './routes/exchange/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TerminalIndexRouteImport } from './routes/terminal/index'
import { Route as ExchangeIndexRouteImport } from './routes/exchange/index'
import { Route as BankIndexRouteImport } from './routes/bank/index'
import { Route as TerminalWatchlistRouteImport } from './routes/terminal/watchlist'
import { Route as TerminalTradeRouteImport } from './routes/terminal/trade'
import { Route as TerminalResearchRouteImport } from './routes/terminal/research'
import { Route as TerminalPortfolioRouteImport } from './routes/terminal/portfolio'
import { Route as TerminalNewsRouteImport } from './routes/terminal/news'
import { Route as TerminalLeaderboardRouteImport } from './routes/terminal/leaderboard'
import { Route as TerminalIpoRouteImport } from './routes/terminal/ipo'
import { Route as ExchangeResearchRouteImport } from './routes/exchange/research'
import { Route as ExchangeRankingsRouteImport } from './routes/exchange/rankings'
import { Route as ExchangeListingsRouteImport } from './routes/exchange/listings'
import { Route as ExchangeIpoRouteImport } from './routes/exchange/ipo'
import { Route as ExchangeIndicesRouteImport } from './routes/exchange/indices'
import { Route as ExchangeApplyRouteImport } from './routes/exchange/apply'
import { Route as ExchangeApiRouteImport } from './routes/exchange/api'
import { Route as ExchangeActionsRouteImport } from './routes/exchange/actions'
import { Route as BankTransfersRouteImport } from './routes/bank/transfers'
import { Route as BankPrivateRouteImport } from './routes/bank/private'
import { Route as BankLendingRouteImport } from './routes/bank/lending'
import { Route as BankDepositsRouteImport } from './routes/bank/deposits'
import { Route as BankDashboardRouteImport } from './routes/bank/dashboard'
import { Route as BankBusinessRouteImport } from './routes/bank/business'
import { Route as BankAccountsRouteImport } from './routes/bank/accounts'
import { Route as BankAdminPrivateRouteImport } from './routes/bank/admin/private'
import { Route as BankAdminLoansRouteImport } from './routes/bank/admin/loans'
import { Route as BankAdminClientsRouteImport } from './routes/bank/admin/clients'
import { Route as ExchangeCompanyTickerRouteRouteImport } from './routes/exchange/company/$ticker/route'
import { Route as ExchangeCompanyTickerIndexRouteImport } from './routes/exchange/company/$ticker/index'
import { Route as ExchangeCompanyTickerOwnerRouteImport } from './routes/exchange/company/$ticker/owner'

const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalRouteRoute = TerminalRouteRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeRouteRoute = ExchangeRouteRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalIndexRoute = TerminalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TerminalRouteRoute,
} as any)
const ExchangeIndexRoute = ExchangeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExchangeRouteRoute,
} as any)
const BankIndexRoute = BankIndexRouteImport.update({
  id: '/bank/',
  path: '/bank/',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalWatchlistRoute = TerminalWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => TerminalRouteRoute,
} as any)
const TerminalTradeRoute = TerminalTradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => TerminalRouteRoute,
} as any)
const TerminalResearchRoute = TerminalResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => TerminalRouteRoute,
} as any)
const TerminalPortfolioRoute = TerminalPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => TerminalRouteRoute,
} as any)
const TerminalNewsRoute = TerminalNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => TerminalRouteRoute,
} as any)
const TerminalLeaderboardRoute = TerminalLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => TerminalRouteRoute,
} as any)
const TerminalIpoRoute = TerminalIpoRouteImport.update({
  id: '/ipo',
  path: '/ipo',
  getParentRoute: () => TerminalRouteRoute,
} as any)
const ExchangeResearchRoute = ExchangeResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => ExchangeRouteRoute,
} as any)
const ExchangeRankingsRoute = ExchangeRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => ExchangeRouteRoute,
} as any)
const ExchangeListingsRoute = ExchangeListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => ExchangeRouteRoute,
} as any)
const ExchangeIpoRoute = ExchangeIpoRouteImport.update({
  id: '/ipo',
  path: '/ipo',
  getParentRoute: () => ExchangeRouteRoute,
} as any)
const ExchangeIndicesRoute = ExchangeIndicesRouteImport.update({
  id: '/indices',
  path: '/indices',
  getParentRoute: () => ExchangeRouteRoute,
} as any)
const ExchangeApplyRoute = ExchangeApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => ExchangeRouteRoute,
} as any)
const ExchangeApiRoute = ExchangeApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => ExchangeRouteRoute,
} as any)
const ExchangeActionsRoute = ExchangeActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => ExchangeRouteRoute,
} as any)
const BankTransfersRoute = BankTransfersRouteImport.update({
  id: '/bank/transfers',
  path: '/bank/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const BankPrivateRoute = BankPrivateRouteImport.update({
  id: '/bank/private',
  path: '/bank/private',
  getParentRoute: () => rootRouteImport,
} as any)
const BankLendingRoute = BankLendingRouteImport.update({
  id: '/bank/lending',
  path: '/bank/lending',
  getParentRoute: () => rootRouteImport,
} as any)
const BankDepositsRoute = BankDepositsRouteImport.update({
  id: '/bank/deposits',
  path: '/bank/deposits',
  getParentRoute: () => rootRouteImport,
} as any)
const BankDashboardRoute = BankDashboardRouteImport.update({
  id: '/bank/dashboard',
  path: '/bank/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BankBusinessRoute = BankBusinessRouteImport.update({
  id: '/bank/business',
  path: '/bank/business',
  getParentRoute: () => rootRouteImport,
} as any)
const BankAccountsRoute = BankAccountsRouteImport.update({
  id: '/bank/accounts',
  path: '/bank/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const BankAdminPrivateRoute = BankAdminPrivateRouteImport.update({
  id: '/bank/admin/private',
  path: '/bank/admin/private',
  getParentRoute: () => rootRouteImport,
} as any)
const BankAdminLoansRoute = BankAdminLoansRouteImport.update({
  id: '/bank/admin/loans',
  path: '/bank/admin/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const BankAdminClientsRoute = BankAdminClientsRouteImport.update({
  id: '/bank/admin/clients',
  path: '/bank/admin/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeCompanyTickerRouteRoute =
  ExchangeCompanyTickerRouteRouteImport.update({
    id: '/company/$ticker',
    path: '/company/$ticker',
    getParentRoute: () => ExchangeRouteRoute,
  } as any)
const ExchangeCompanyTickerIndexRoute =
  ExchangeCompanyTickerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ExchangeCompanyTickerRouteRoute,
  } as any)
const ExchangeCompanyTickerOwnerRoute =
  ExchangeCompanyTickerOwnerRouteImport.update({
    id: '/owner',
    path: '/owner',
    getParentRoute: () => ExchangeCompanyTickerRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exchange': typeof ExchangeRouteRouteWithChildren
  '/terminal': typeof TerminalRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/governance': typeof GovernanceRoute
  '/markets': typeof MarketsRoute
  '/bank/accounts': typeof BankAccountsRoute
  '/bank/business': typeof BankBusinessRoute
  '/bank/dashboard': typeof BankDashboardRoute
  '/bank/deposits': typeof BankDepositsRoute
  '/bank/lending': typeof BankLendingRoute
  '/bank/private': typeof BankPrivateRoute
  '/bank/transfers': typeof BankTransfersRoute
  '/exchange/actions': typeof ExchangeActionsRoute
  '/exchange/api': typeof ExchangeApiRoute
  '/exchange/apply': typeof ExchangeApplyRoute
  '/exchange/indices': typeof ExchangeIndicesRoute
  '/exchange/ipo': typeof ExchangeIpoRoute
  '/exchange/listings': typeof ExchangeListingsRoute
  '/exchange/rankings': typeof ExchangeRankingsRoute
  '/exchange/research': typeof ExchangeResearchRoute
  '/terminal/ipo': typeof TerminalIpoRoute
  '/terminal/leaderboard': typeof TerminalLeaderboardRoute
  '/terminal/news': typeof TerminalNewsRoute
  '/terminal/portfolio': typeof TerminalPortfolioRoute
  '/terminal/research': typeof TerminalResearchRoute
  '/terminal/trade': typeof TerminalTradeRoute
  '/terminal/watchlist': typeof TerminalWatchlistRoute
  '/bank/': typeof BankIndexRoute
  '/exchange/': typeof ExchangeIndexRoute
  '/terminal/': typeof TerminalIndexRoute
  '/exchange/company/$ticker': typeof ExchangeCompanyTickerRouteRouteWithChildren
  '/bank/admin/clients': typeof BankAdminClientsRoute
  '/bank/admin/loans': typeof BankAdminLoansRoute
  '/bank/admin/private': typeof BankAdminPrivateRoute
  '/exchange/company/$ticker/owner': typeof ExchangeCompanyTickerOwnerRoute
  '/exchange/company/$ticker/': typeof ExchangeCompanyTickerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/governance': typeof GovernanceRoute
  '/markets': typeof MarketsRoute
  '/bank/accounts': typeof BankAccountsRoute
  '/bank/business': typeof BankBusinessRoute
  '/bank/dashboard': typeof BankDashboardRoute
  '/bank/deposits': typeof BankDepositsRoute
  '/bank/lending': typeof BankLendingRoute
  '/bank/private': typeof BankPrivateRoute
  '/bank/transfers': typeof BankTransfersRoute
  '/exchange/actions': typeof ExchangeActionsRoute
  '/exchange/api': typeof ExchangeApiRoute
  '/exchange/apply': typeof ExchangeApplyRoute
  '/exchange/indices': typeof ExchangeIndicesRoute
  '/exchange/ipo': typeof ExchangeIpoRoute
  '/exchange/listings': typeof ExchangeListingsRoute
  '/exchange/rankings': typeof ExchangeRankingsRoute
  '/exchange/research': typeof ExchangeResearchRoute
  '/terminal/ipo': typeof TerminalIpoRoute
  '/terminal/leaderboard': typeof TerminalLeaderboardRoute
  '/terminal/news': typeof TerminalNewsRoute
  '/terminal/portfolio': typeof TerminalPortfolioRoute
  '/terminal/research': typeof TerminalResearchRoute
  '/terminal/trade': typeof TerminalTradeRoute
  '/terminal/watchlist': typeof TerminalWatchlistRoute
  '/bank': typeof BankIndexRoute
  '/exchange': typeof ExchangeIndexRoute
  '/terminal': typeof TerminalIndexRoute
  '/bank/admin/clients': typeof BankAdminClientsRoute
  '/bank/admin/loans': typeof BankAdminLoansRoute
  '/bank/admin/private': typeof BankAdminPrivateRoute
  '/exchange/company/$ticker/owner': typeof ExchangeCompanyTickerOwnerRoute
  '/exchange/company/$ticker': typeof ExchangeCompanyTickerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exchange': typeof ExchangeRouteRouteWithChildren
  '/terminal': typeof TerminalRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/governance': typeof GovernanceRoute
  '/markets': typeof MarketsRoute
  '/bank/accounts': typeof BankAccountsRoute
  '/bank/business': typeof BankBusinessRoute
  '/bank/dashboard': typeof BankDashboardRoute
  '/bank/deposits': typeof BankDepositsRoute
  '/bank/lending': typeof BankLendingRoute
  '/bank/private': typeof BankPrivateRoute
  '/bank/transfers': typeof BankTransfersRoute
  '/exchange/actions': typeof ExchangeActionsRoute
  '/exchange/api': typeof ExchangeApiRoute
  '/exchange/apply': typeof ExchangeApplyRoute
  '/exchange/indices': typeof ExchangeIndicesRoute
  '/exchange/ipo': typeof ExchangeIpoRoute
  '/exchange/listings': typeof ExchangeListingsRoute
  '/exchange/rankings': typeof ExchangeRankingsRoute
  '/exchange/research': typeof ExchangeResearchRoute
  '/terminal/ipo': typeof TerminalIpoRoute
  '/terminal/leaderboard': typeof TerminalLeaderboardRoute
  '/terminal/news': typeof TerminalNewsRoute
  '/terminal/portfolio': typeof TerminalPortfolioRoute
  '/terminal/research': typeof TerminalResearchRoute
  '/terminal/trade': typeof TerminalTradeRoute
  '/terminal/watchlist': typeof TerminalWatchlistRoute
  '/bank/': typeof BankIndexRoute
  '/exchange/': typeof ExchangeIndexRoute
  '/terminal/': typeof TerminalIndexRoute
  '/exchange/company/$ticker': typeof ExchangeCompanyTickerRouteRouteWithChildren
  '/bank/admin/clients': typeof BankAdminClientsRoute
  '/bank/admin/loans': typeof BankAdminLoansRoute
  '/bank/admin/private': typeof BankAdminPrivateRoute
  '/exchange/company/$ticker/owner': typeof ExchangeCompanyTickerOwnerRoute
  '/exchange/company/$ticker/': typeof ExchangeCompanyTickerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exchange'
    | '/terminal'
    | '/dashboard'
    | '/governance'
    | '/markets'
    | '/bank/accounts'
    | '/bank/business'
    | '/bank/dashboard'
    | '/bank/deposits'
    | '/bank/lending'
    | '/bank/private'
    | '/bank/transfers'
    | '/exchange/actions'
    | '/exchange/api'
    | '/exchange/apply'
    | '/exchange/indices'
    | '/exchange/ipo'
    | '/exchange/listings'
    | '/exchange/rankings'
    | '/exchange/research'
    | '/terminal/ipo'
    | '/terminal/leaderboard'
    | '/terminal/news'
    | '/terminal/portfolio'
    | '/terminal/research'
    | '/terminal/trade'
    | '/terminal/watchlist'
    | '/bank/'
    | '/exchange/'
    | '/terminal/'
    | '/exchange/company/$ticker'
    | '/bank/admin/clients'
    | '/bank/admin/loans'
    | '/bank/admin/private'
    | '/exchange/company/$ticker/owner'
    | '/exchange/company/$ticker/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/governance'
    | '/markets'
    | '/bank/accounts'
    | '/bank/business'
    | '/bank/dashboard'
    | '/bank/deposits'
    | '/bank/lending'
    | '/bank/private'
    | '/bank/transfers'
    | '/exchange/actions'
    | '/exchange/api'
    | '/exchange/apply'
    | '/exchange/indices'
    | '/exchange/ipo'
    | '/exchange/listings'
    | '/exchange/rankings'
    | '/exchange/research'
    | '/terminal/ipo'
    | '/terminal/leaderboard'
    | '/terminal/news'
    | '/terminal/portfolio'
    | '/terminal/research'
    | '/terminal/trade'
    | '/terminal/watchlist'
    | '/bank'
    | '/exchange'
    | '/terminal'
    | '/bank/admin/clients'
    | '/bank/admin/loans'
    | '/bank/admin/private'
    | '/exchange/company/$ticker/owner'
    | '/exchange/company/$ticker'
  id:
    | '__root__'
    | '/'
    | '/exchange'
    | '/terminal'
    | '/dashboard'
    | '/governance'
    | '/markets'
    | '/bank/accounts'
    | '/bank/business'
    | '/bank/dashboard'
    | '/bank/deposits'
    | '/bank/lending'
    | '/bank/private'
    | '/bank/transfers'
    | '/exchange/actions'
    | '/exchange/api'
    | '/exchange/apply'
    | '/exchange/indices'
    | '/exchange/ipo'
    | '/exchange/listings'
    | '/exchange/rankings'
    | '/exchange/research'
    | '/terminal/ipo'
    | '/terminal/leaderboard'
    | '/terminal/news'
    | '/terminal/portfolio'
    | '/terminal/research'
    | '/terminal/trade'
    | '/terminal/watchlist'
    | '/bank/'
    | '/exchange/'
    | '/terminal/'
    | '/exchange/company/$ticker'
    | '/bank/admin/clients'
    | '/bank/admin/loans'
    | '/bank/admin/private'
    | '/exchange/company/$ticker/owner'
    | '/exchange/company/$ticker/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExchangeRouteRoute: typeof ExchangeRouteRouteWithChildren
  TerminalRouteRoute: typeof TerminalRouteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  GovernanceRoute: typeof GovernanceRoute
  MarketsRoute: typeof MarketsRoute
  BankAccountsRoute: typeof BankAccountsRoute
  BankBusinessRoute: typeof BankBusinessRoute
  BankDashboardRoute: typeof BankDashboardRoute
  BankDepositsRoute: typeof BankDepositsRoute
  BankLendingRoute: typeof BankLendingRoute
  BankPrivateRoute: typeof BankPrivateRoute
  BankTransfersRoute: typeof BankTransfersRoute
  BankIndexRoute: typeof BankIndexRoute
  BankAdminClientsRoute: typeof BankAdminClientsRoute
  BankAdminLoansRoute: typeof BankAdminLoansRoute
  BankAdminPrivateRoute: typeof BankAdminPrivateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange': {
      id: '/exchange'
      path: '/exchange'
      fullPath: '/exchange'
      preLoaderRoute: typeof ExchangeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal/': {
      id: '/terminal/'
      path: '/'
      fullPath: '/terminal/'
      preLoaderRoute: typeof TerminalIndexRouteImport
      parentRoute: typeof TerminalRouteRoute
    }
    '/exchange/': {
      id: '/exchange/'
      path: '/'
      fullPath: '/exchange/'
      preLoaderRoute: typeof ExchangeIndexRouteImport
      parentRoute: typeof ExchangeRouteRoute
    }
    '/bank/': {
      id: '/bank/'
      path: '/bank'
      fullPath: '/bank/'
      preLoaderRoute: typeof BankIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal/watchlist': {
      id: '/terminal/watchlist'
      path: '/watchlist'
      fullPath: '/terminal/watchlist'
      preLoaderRoute: typeof TerminalWatchlistRouteImport
      parentRoute: typeof TerminalRouteRoute
    }
    '/terminal/trade': {
      id: '/terminal/trade'
      path: '/trade'
      fullPath: '/terminal/trade'
      preLoaderRoute: typeof TerminalTradeRouteImport
      parentRoute: typeof TerminalRouteRoute
    }
    '/terminal/research': {
      id: '/terminal/research'
      path: '/research'
      fullPath: '/terminal/research'
      preLoaderRoute: typeof TerminalResearchRouteImport
      parentRoute: typeof TerminalRouteRoute
    }
    '/terminal/portfolio': {
      id: '/terminal/portfolio'
      path: '/portfolio'
      fullPath: '/terminal/portfolio'
      preLoaderRoute: typeof TerminalPortfolioRouteImport
      parentRoute: typeof TerminalRouteRoute
    }
    '/terminal/news': {
      id: '/terminal/news'
      path: '/news'
      fullPath: '/terminal/news'
      preLoaderRoute: typeof TerminalNewsRouteImport
      parentRoute: typeof TerminalRouteRoute
    }
    '/terminal/leaderboard': {
      id: '/terminal/leaderboard'
      path: '/leaderboard'
      fullPath: '/terminal/leaderboard'
      preLoaderRoute: typeof TerminalLeaderboardRouteImport
      parentRoute: typeof TerminalRouteRoute
    }
    '/terminal/ipo': {
      id: '/terminal/ipo'
      path: '/ipo'
      fullPath: '/terminal/ipo'
      preLoaderRoute: typeof TerminalIpoRouteImport
      parentRoute: typeof TerminalRouteRoute
    }
    '/exchange/research': {
      id: '/exchange/research'
      path: '/research'
      fullPath: '/exchange/research'
      preLoaderRoute: typeof ExchangeResearchRouteImport
      parentRoute: typeof ExchangeRouteRoute
    }
    '/exchange/rankings': {
      id: '/exchange/rankings'
      path: '/rankings'
      fullPath: '/exchange/rankings'
      preLoaderRoute: typeof ExchangeRankingsRouteImport
      parentRoute: typeof ExchangeRouteRoute
    }
    '/exchange/listings': {
      id: '/exchange/listings'
      path: '/listings'
      fullPath: '/exchange/listings'
      preLoaderRoute: typeof ExchangeListingsRouteImport
      parentRoute: typeof ExchangeRouteRoute
    }
    '/exchange/ipo': {
      id: '/exchange/ipo'
      path: '/ipo'
      fullPath: '/exchange/ipo'
      preLoaderRoute: typeof ExchangeIpoRouteImport
      parentRoute: typeof ExchangeRouteRoute
    }
    '/exchange/indices': {
      id: '/exchange/indices'
      path: '/indices'
      fullPath: '/exchange/indices'
      preLoaderRoute: typeof ExchangeIndicesRouteImport
      parentRoute: typeof ExchangeRouteRoute
    }
    '/exchange/apply': {
      id: '/exchange/apply'
      path: '/apply'
      fullPath: '/exchange/apply'
      preLoaderRoute: typeof ExchangeApplyRouteImport
      parentRoute: typeof ExchangeRouteRoute
    }
    '/exchange/api': {
      id: '/exchange/api'
      path: '/api'
      fullPath: '/exchange/api'
      preLoaderRoute: typeof ExchangeApiRouteImport
      parentRoute: typeof ExchangeRouteRoute
    }
    '/exchange/actions': {
      id: '/exchange/actions'
      path: '/actions'
      fullPath: '/exchange/actions'
      preLoaderRoute: typeof ExchangeActionsRouteImport
      parentRoute: typeof ExchangeRouteRoute
    }
    '/bank/transfers': {
      id: '/bank/transfers'
      path: '/bank/transfers'
      fullPath: '/bank/transfers'
      preLoaderRoute: typeof BankTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank/private': {
      id: '/bank/private'
      path: '/bank/private'
      fullPath: '/bank/private'
      preLoaderRoute: typeof BankPrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank/lending': {
      id: '/bank/lending'
      path: '/bank/lending'
      fullPath: '/bank/lending'
      preLoaderRoute: typeof BankLendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank/deposits': {
      id: '/bank/deposits'
      path: '/bank/deposits'
      fullPath: '/bank/deposits'
      preLoaderRoute: typeof BankDepositsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank/dashboard': {
      id: '/bank/dashboard'
      path: '/bank/dashboard'
      fullPath: '/bank/dashboard'
      preLoaderRoute: typeof BankDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank/business': {
      id: '/bank/business'
      path: '/bank/business'
      fullPath: '/bank/business'
      preLoaderRoute: typeof BankBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank/accounts': {
      id: '/bank/accounts'
      path: '/bank/accounts'
      fullPath: '/bank/accounts'
      preLoaderRoute: typeof BankAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank/admin/private': {
      id: '/bank/admin/private'
      path: '/bank/admin/private'
      fullPath: '/bank/admin/private'
      preLoaderRoute: typeof BankAdminPrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank/admin/loans': {
      id: '/bank/admin/loans'
      path: '/bank/admin/loans'
      fullPath: '/bank/admin/loans'
      preLoaderRoute: typeof BankAdminLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank/admin/clients': {
      id: '/bank/admin/clients'
      path: '/bank/admin/clients'
      fullPath: '/bank/admin/clients'
      preLoaderRoute: typeof BankAdminClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange/company/$ticker': {
      id: '/exchange/company/$ticker'
      path: '/company/$ticker'
      fullPath: '/exchange/company/$ticker'
      preLoaderRoute: typeof ExchangeCompanyTickerRouteRouteImport
      parentRoute: typeof ExchangeRouteRoute
    }
    '/exchange/company/$ticker/': {
      id: '/exchange/company/$ticker/'
      path: '/'
      fullPath: '/exchange/company/$ticker/'
      preLoaderRoute: typeof ExchangeCompanyTickerIndexRouteImport
      parentRoute: typeof ExchangeCompanyTickerRouteRoute
    }
    '/exchange/company/$ticker/owner': {
      id: '/exchange/company/$ticker/owner'
      path: '/owner'
      fullPath: '/exchange/company/$ticker/owner'
      preLoaderRoute: typeof ExchangeCompanyTickerOwnerRouteImport
      parentRoute: typeof ExchangeCompanyTickerRouteRoute
    }
  }
}

interface ExchangeCompanyTickerRouteRouteChildren {
  ExchangeCompanyTickerOwnerRoute: typeof ExchangeCompanyTickerOwnerRoute
  ExchangeCompanyTickerIndexRoute: typeof ExchangeCompanyTickerIndexRoute
}

const ExchangeCompanyTickerRouteRouteChildren: ExchangeCompanyTickerRouteRouteChildren =
  {
    ExchangeCompanyTickerOwnerRoute: ExchangeCompanyTickerOwnerRoute,
    ExchangeCompanyTickerIndexRoute: ExchangeCompanyTickerIndexRoute,
  }

const ExchangeCompanyTickerRouteRouteWithChildren =
  ExchangeCompanyTickerRouteRoute._addFileChildren(
    ExchangeCompanyTickerRouteRouteChildren,
  )

interface ExchangeRouteRouteChildren {
  ExchangeActionsRoute: typeof ExchangeActionsRoute
  ExchangeApiRoute: typeof ExchangeApiRoute
  ExchangeApplyRoute: typeof ExchangeApplyRoute
  ExchangeIndicesRoute: typeof ExchangeIndicesRoute
  ExchangeIpoRoute: typeof ExchangeIpoRoute
  ExchangeListingsRoute: typeof ExchangeListingsRoute
  ExchangeRankingsRoute: typeof ExchangeRankingsRoute
  ExchangeResearchRoute: typeof ExchangeResearchRoute
  ExchangeIndexRoute: typeof ExchangeIndexRoute
  ExchangeCompanyTickerRouteRoute: typeof ExchangeCompanyTickerRouteRouteWithChildren
}

const ExchangeRouteRouteChildren: ExchangeRouteRouteChildren = {
  ExchangeActionsRoute: ExchangeActionsRoute,
  ExchangeApiRoute: ExchangeApiRoute,
  ExchangeApplyRoute: ExchangeApplyRoute,
  ExchangeIndicesRoute: ExchangeIndicesRoute,
  ExchangeIpoRoute: ExchangeIpoRoute,
  ExchangeListingsRoute: ExchangeListingsRoute,
  ExchangeRankingsRoute: ExchangeRankingsRoute,
  ExchangeResearchRoute: ExchangeResearchRoute,
  ExchangeIndexRoute: ExchangeIndexRoute,
  ExchangeCompanyTickerRouteRoute: ExchangeCompanyTickerRouteRouteWithChildren,
}

const ExchangeRouteRouteWithChildren = ExchangeRouteRoute._addFileChildren(
  ExchangeRouteRouteChildren,
)

interface TerminalRouteRouteChildren {
  TerminalIpoRoute: typeof TerminalIpoRoute
  TerminalLeaderboardRoute: typeof TerminalLeaderboardRoute
  TerminalNewsRoute: typeof TerminalNewsRoute
  TerminalPortfolioRoute: typeof TerminalPortfolioRoute
  TerminalResearchRoute: typeof TerminalResearchRoute
  TerminalTradeRoute: typeof TerminalTradeRoute
  TerminalWatchlistRoute: typeof TerminalWatchlistRoute
  TerminalIndexRoute: typeof TerminalIndexRoute
}

const TerminalRouteRouteChildren: TerminalRouteRouteChildren = {
  TerminalIpoRoute: TerminalIpoRoute,
  TerminalLeaderboardRoute: TerminalLeaderboardRoute,
  TerminalNewsRoute: TerminalNewsRoute,
  TerminalPortfolioRoute: TerminalPortfolioRoute,
  TerminalResearchRoute: TerminalResearchRoute,
  TerminalTradeRoute: TerminalTradeRoute,
  TerminalWatchlistRoute: TerminalWatchlistRoute,
  TerminalIndexRoute: TerminalIndexRoute,
}

const TerminalRouteRouteWithChildren = TerminalRouteRoute._addFileChildren(
  TerminalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExchangeRouteRoute: ExchangeRouteRouteWithChildren,
  TerminalRouteRoute: TerminalRouteRouteWithChildren,
  DashboardRoute: DashboardRoute,
  GovernanceRoute: GovernanceRoute,
  MarketsRoute: MarketsRoute,
  BankAccountsRoute: BankAccountsRoute,
  BankBusinessRoute: BankBusinessRoute,
  BankDashboardRoute: BankDashboardRoute,
  BankDepositsRoute: BankDepositsRoute,
  BankLendingRoute: BankLendingRoute,
  BankPrivateRoute: BankPrivateRoute,
  BankTransfersRoute: BankTransfersRoute,
  BankIndexRoute: BankIndexRoute,
  BankAdminClientsRoute: BankAdminClientsRoute,
  BankAdminLoansRoute: BankAdminLoansRoute,
  BankAdminPrivateRoute: BankAdminPrivateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
