-- Notification types for payment lifecycle and delivery tracking
ALTER TYPE "UserNotificationType" ADD VALUE IF NOT EXISTS 'TRANSFER_FAILED';
ALTER TYPE "UserNotificationType" ADD VALUE IF NOT EXISTS 'ALTA_PAY_FAILED';
ALTER TYPE "UserNotificationType" ADD VALUE IF NOT EXISTS 'SCHEDULED_TRANSFER_EXECUTED';
ALTER TYPE "UserNotificationType" ADD VALUE IF NOT EXISTS 'SCHEDULED_TRANSFER_FAILED';
ALTER TYPE "UserNotificationType" ADD VALUE IF NOT EXISTS 'LOAN_PAYMENT_MADE';
ALTER TYPE "UserNotificationType" ADD VALUE IF NOT EXISTS 'LOAN_PAID_OFF';
ALTER TYPE "UserNotificationType" ADD VALUE IF NOT EXISTS 'LOAN_AUTOPAY_FAILED';
ALTER TYPE "UserNotificationType" ADD VALUE IF NOT EXISTS 'ALTA_CARD_PAYMENT_MADE';
ALTER TYPE "UserNotificationType" ADD VALUE IF NOT EXISTS 'ALTA_CARD_AUTOPAY_SUCCEEDED';
ALTER TYPE "UserNotificationType" ADD VALUE IF NOT EXISTS 'ALTA_CARD_AUTOPAY_FAILED';
ALTER TYPE "UserNotificationType" ADD VALUE IF NOT EXISTS 'ALTA_CARD_REVIEW_DECIDED';
ALTER TYPE "UserNotificationType" ADD VALUE IF NOT EXISTS 'ALTA_CARD_ACTIVATED';
ALTER TYPE "UserNotificationType" ADD VALUE IF NOT EXISTS 'COMPANY_VERIFIED';
ALTER TYPE "UserNotificationType" ADD VALUE IF NOT EXISTS 'COMPANY_ROLE_CHANGED';

ALTER TABLE "UserNotification" ADD COLUMN IF NOT EXISTS "discordNotifiedAt" TIMESTAMP(3);
